name: Build & Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-build:
    runs-on: self-hosted
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest@sha256:5d6a17640b25694988b9db5a4145537b9918e5430116b2cf90d84e837609b382

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: https://github.com/cachix/install-nix-action@630ae543ea3a38a9a4166f03376c02c50f408342 # v31

      - name: Setup Attic
        id: attic
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_KEY }}
          ATTIC_ENDPOINT: ${{ vars.ATTIC_ENDPOINT }}
          ATTIC_STORE: ${{ vars.ATTIC_STORE }}
        run: |
          nix shell nixpkgs#attic-client -c sh -c '
            attic login "$ATTIC_STORE" "$ATTIC_ENDPOINT" "$ATTIC_TOKEN"
            attic use "$ATTIC_STORE"
          '

      - name: Build & Checks
        run: |
          nix flake check . -L --no-update-lock-file

      - name: Push to Attic
        if: always()
        env:
          ATTIC_STORE: ${{ vars.ATTIC_STORE }}
        run: |
          nix shell nixpkgs#attic-client -c sh -c '
            attic push "$ATTIC_STORE" --ignore-upstream-cache-filter -j 64 $(ls -d /nix/store/*/)
          '
