name: Build & Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-build:
    runs-on: self-hosted
    container:
      image: ghcr.io/catthehacker/ubuntu:act-latest@sha256:62d572b92f9f32d3427b6d220ad1f9dca9c7b6ffad37d295425037dbff78abaf

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: https://github.com/cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31

      - name: Setup Attic
        id: attic
        env:
          ATTIC_TOKEN: ${{ secrets.ATTIC_KEY }}
          ATTIC_ENDPOINT: ${{ vars.ATTIC_ENDPOINT }}
          ATTIC_STORE: ${{ vars.ATTIC_STORE }}
        run: |
          nix shell nixpkgs#attic-client -c sh -c '
            attic login "$ATTIC_STORE" "$ATTIC_ENDPOINT" "$ATTIC_TOKEN"
            attic use "$ATTIC_STORE"
          '

      - name: Build & Checks
        run: |
          nix flake check . -L --no-update-lock-file

      - name: Push to Attic
        if: always()
        env:
          ATTIC_STORE: ${{ vars.ATTIC_STORE }}
        run: |
          nix shell nixpkgs#attic-client -c sh -c '
            attic push "$ATTIC_STORE" --ignore-upstream-cache-filter -j 64 $(ls -d /nix/store/*/)
          '
