[[webhooks]]
name = "test_webhook"
url = "https://amber-dog-91.webhook.cool"

[webhooks.formatter]
script = """
function(data)
    local msg = data.message or "no message"
    local chars = {}

    for i = 1, #msg do
        chars[i] = string.sub(msg, i, i)
    end

    return {
        body = "Alert: " .. (data.message or "no message"),
        message_chars = chars,
        timestamp = data.timestamp or os.time(),
    }
end
"""

[inputs.test_input]
token_file = "./test_data/token.txt"
fallback_target = "test_webhook"
rules = []
